name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo $GITHUB_SHA)
      - name: Build the tagged Docker image
        run: |
          for image in $(find . -type d -exec [ -e {}/Dockerfile ] \; -print -prune | sed -e 's#^\./##' -e 's#/$##' -e 's#/#-#g'); do
            echo "cd $image && docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/$image:${{ steps.vars.outputs.tag }} ."
          done
