name: Docker Image Build CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo $GITHUB_SHA)
      - name: Build the tagged Docker image
        run: |
          repo_root_dir="$PWD"
          for image_path in $(find . -type d -exec [ -e {}/Dockerfile ] \; -print -prune); do
            image="$(echo $image_path | sed -e 's#^\./##' -e 's#/$##' -e 's#/#-#g')"
            cd "$image_path"
            docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/$image:${{ steps.vars.outputs.tag }} .
            cd "$repo_root_dir"
          done
