name: Python Image CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g')"
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: |
            cd cicd/python
            docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:latest .
            version="$(docker inspect ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:latest | jq -r .[0].ContainerConfig.Labels.Version)"
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:latest ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:$version
      - name: Push the tagged Docker image
        run: |
          cd cicd/python
          if [ "${{ steps.branch.outputs.branch }}" == "master" ]; then
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:latest
            version="$(docker inspect ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:latest | jq -r .[0].ContainerConfig.Labels.Version)"
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-python:$version
          fi
